version: '3.1'
services:
  percona-server:
    container_name: percona
    image: percona/percona-server:8.0
    restart: always
    volumes: 
      - percona_db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=IsolationDB
  
  postgres:
    container_name: postgres
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      PGDATA: /data/postgres
    volumes:
       - postgres_db:/data/postgres
    ports:
      - 5432:5432

volumes:
  percona_db : {}
  postgres_db : {}